language: java
install: true

jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

script:
- ./gradlew cleanTest test jacocoTestReport cucumber
- sonar-scanner

addons:
  sonarcloud:
    organization: "pascalstalder-github"
    token:
      secure: d24356e7d015dbc7a978f933c6277982b20685a1
